language: java
jdk: oraclejdk9

env:
  - TARGET="ui"
  - TARGET="service/cart"
  - TARGET="service/user"
  - TARGET="repository/order"
  - TARGET="repository/cart"
  - TARGET="repository/product"
  - TARGET="repository/user"

before_script:
  - ./gradlew clean jar

script:
  - COVERAGE=0.24 ./gradlew -p /monolithic/$(TARGET) check

deploy:
  provider: script
  script: echo "WIP"
  on:
    all_branches: true