language: java
jdk:oraclejdk9

stages:
  - test

jobs:
  include:
    - stage: test
      install: ./gradlew clean jar
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=0.050
        TARGET="ui"
    - stage: test
      install: ./gradlew clean jar
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=0.140
        TARGET="service/cart"
    - stage: test
      install: ./gradlew clean jar
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=0.00
        TARGET="service/user"
    - stage: test
      install: ./gradlew clean jar
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=0.24
        TARGET="repository/order"
    - stage: test
      install: ./gradlew clean jar
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=0.00
        TARGET="repository/cart"
    - stage: test
      install: ./gradlew clean jar
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=0.120
        TARGET="repository/product"
    - stage: test
      install: ./gradlew clean jar
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=0.24
        TARGET="repository/user"

deploy:
  provider: script
  script: echo "WIP"
  on:
    all_branches: true