language: java
jdk: oraclejdk9

target_rep:
  - "ui"
  - "service/cart"
  - "service/user"
  - "repository/order"
  - "repository/cart"
  - "repository/product"
  - "repository/user"

before_script:
  - ./gradlew clean jar

script:
  - COVERAGE=0.24 ./gradlew -p /monolothic/$(target_rep) check

deploy:
  provider: script
  script: echo "WIP"
  on:
    all_branches: true