language: java
jdk: oraclejdk9

env:
  - TARGET="/monolithic/ui"
  - TARGET="/monolithic/service/cart"
  - TARGET="/monolithic/service/user"
  - TARGET="/monolithic/repository/order"
  - TARGET="/monolithic/repository/cart"
  - TARGET="/monolithic/repository/product"
  - TARGET="/monolithic/repository/user"

before_script:
  - ./gradlew clean jar

script:
  - COVERAGE=0.24 ./gradlew -p $TARGET check

deploy:
  provider: script
  script: echo "WIP"
  on:
    all_branches: true