language: java
jdk:
  - oraclejdk9
  - oraclejdk10

before_script:
  - ./gradlew clean jar


jobs:
  include:
    - stage: test
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=$COVERAGE=0.050
        $TARGET="ui"
    - stage: test
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=$COVERAGE=0.140
        $TARGET="service/cart"
    - stage: test
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=$COVERAGE=0.00
        $TARGET="service/user"
    - stage: test
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=$COVERAGE=0.24
        $TARGET="repository/order"
    - stage: test
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=$COVERAGE=0.00
        $TARGET="repository/cart"
    - stage: test
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=$COVERAGE=0.120
        $TARGET="repository/product"
    - stage: test
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      env:
        COVERAGE=$COVERAGE=0.24
        $TARGET="repository/user"

deploy:
  provider: script
  script: echo "WIP"
  on:
    all_branches: true